# yaml-language-server: $schema=https://raw.githubusercontent.com/edelwud/terraci/main/terraci.schema.json
structure:
  pattern: "{service}/{environment}/{region}/{module}"

execution:
  binary: terraform
  init_enabled: true
  plan_enabled: true

extensions:
  github:
    runs_on: ubuntu-latest
    auto_approve: false

    permissions:
      contents: read
      pull-requests: write
      id-token: write

    job_defaults:
      steps_before:
        - uses: actions/checkout@v4
        - uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "1.6"
        - uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::role/terraform
            aws-region: eu-central-1

    pr:
      comment:
        enabled: true

  cost:
    providers:
      aws:
        enabled: true
