package test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerate_GitLabPipeline(t *testing.T) {
	dir := fixtureDir(t, "basic")
	outFile := filepath.Join(t.TempDir(), "pipeline.yaml")

	err := runTerraCi(t, dir, "generate", "-o", outFile)
	if err != nil {
		t.Fatalf("generate failed: %v", err)
	}

	data, readErr := os.ReadFile(outFile)
	if readErr != nil {
		t.Fatalf("failed to read output: %v", readErr)
	}
	output := string(data)

	// Should contain terraci header
	if !strings.Contains(output, "Generated by terraci") {
		t.Error("missing terraci header in output")
	}

	// Should contain stages
	if !strings.Contains(output, "stages:") {
		t.Error("missing stages in output")
	}

	// Should contain plan jobs for modules
	if !strings.Contains(output, "plan") {
		t.Error("missing plan jobs in output")
	}

	// Should contain apply jobs
	if !strings.Contains(output, "apply") {
		t.Error("missing apply jobs in output")
	}

	// Should reference all 4 modules (vpc x2, eks, app)
	expectedModules := []string{"vpc", "eks", "app"}
	for _, mod := range expectedModules {
		if !strings.Contains(output, mod) {
			t.Errorf("output missing module reference: %s", mod)
		}
	}

	// Parse YAML structure and validate
	pipeline := parseYAML(t, output)

	stages, ok := pipeline["stages"].([]any)
	if !ok || len(stages) == 0 {
		t.Fatal("missing or empty stages in parsed YAML")
	}

	// Check specific job names follow naming convention
	assertContains(t, output, "plan-platform-prod-eu-central-1-vpc")
	assertContains(t, output, "plan-platform-prod-eu-central-1-eks")
	assertContains(t, output, "apply-platform-prod-eu-central-1-vpc")
	assertContains(t, output, "apply-platform-prod-eu-central-1-eks")
}

func TestGenerate_PlanOnly(t *testing.T) {
	dir := fixtureDir(t, "basic")
	outFile := filepath.Join(t.TempDir(), "pipeline.yaml")

	err := runTerraCi(t, dir, "generate", "--plan-only", "-o", outFile)
	if err != nil {
		t.Fatalf("generate --plan-only failed: %v", err)
	}

	data, readErr := os.ReadFile(outFile)
	if readErr != nil {
		t.Fatalf("failed to read output: %v", readErr)
	}
	output := string(data)

	// Should contain plan jobs with specific naming convention
	assertContains(t, output, "plan-platform-prod-eu-central-1-vpc")
	assertContains(t, output, "plan-platform-stage-eu-central-1-vpc")

	// Should be valid YAML with terraci header
	assertContains(t, output, "Generated by terraci")

	// Parse YAML to confirm valid structure
	pipeline := parseYAML(t, output)
	stages, ok := pipeline["stages"].([]any)
	if !ok || len(stages) == 0 {
		t.Fatal("plan-only output missing stages")
	}

	// Verify plan stages exist
	hasPlanStage := false
	for _, s := range stages {
		if str, ok := s.(string); ok && strings.Contains(str, "plan") {
			hasPlanStage = true
			break
		}
	}
	if !hasPlanStage {
		t.Error("plan-only output should have plan stages")
	}
}

func TestGenerate_DryRun(t *testing.T) {
	dir := fixtureDir(t, "basic")

	// dry-run should succeed without error (output goes to log, not stdout)
	err := runTerraCi(t, dir, "generate", "--dry-run")
	if err != nil {
		t.Fatalf("generate --dry-run failed: %v", err)
	}
}

func TestGenerate_OutputToStdout(t *testing.T) {
	dir := fixtureDir(t, "basic")

	output, err := captureTerraCi(t, dir, "generate")
	if err != nil {
		t.Fatalf("generate (stdout) failed: %v", err)
	}

	assertContains(t, output, "Generated by terraci")
	assertContains(t, output, "stages:")
	assertContains(t, output, "plan-")

	// Parse YAML to confirm valid structure on stdout path too
	pipeline := parseYAML(t, output)
	if _, ok := pipeline["stages"]; !ok {
		t.Error("stdout output missing stages in parsed YAML")
	}
}
