package test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerate_GitLabPipeline(t *testing.T) {
	dir := fixtureDir(t, "basic")
	outFile := filepath.Join(t.TempDir(), "pipeline.yaml")

	err := runTerraCi(t, dir, "generate", "-o", outFile)
	if err != nil {
		t.Fatalf("generate failed: %v", err)
	}

	data, readErr := os.ReadFile(outFile)
	if readErr != nil {
		t.Fatalf("failed to read output: %v", readErr)
	}
	output := string(data)

	// Should contain terraci header
	if !strings.Contains(output, "Generated by terraci") {
		t.Error("missing terraci header in output")
	}

	// Should contain stages
	if !strings.Contains(output, "stages:") {
		t.Error("missing stages in output")
	}

	// Should contain plan jobs for modules
	if !strings.Contains(output, "plan") {
		t.Error("missing plan jobs in output")
	}

	// Should contain apply jobs
	if !strings.Contains(output, "apply") {
		t.Error("missing apply jobs in output")
	}

	// Should reference all 4 modules (vpc x2, eks, app)
	expectedModules := []string{"vpc", "eks", "app"}
	for _, mod := range expectedModules {
		if !strings.Contains(output, mod) {
			t.Errorf("output missing module reference: %s", mod)
		}
	}
}

func TestGenerate_PlanOnly(t *testing.T) {
	dir := fixtureDir(t, "basic")
	outFile := filepath.Join(t.TempDir(), "pipeline.yaml")

	err := runTerraCi(t, dir, "generate", "--plan-only", "-o", outFile)
	if err != nil {
		t.Fatalf("generate --plan-only failed: %v", err)
	}

	data, readErr := os.ReadFile(outFile)
	if readErr != nil {
		t.Fatalf("failed to read output: %v", readErr)
	}
	output := string(data)

	// Should contain plan jobs
	if !strings.Contains(output, "plan") {
		t.Error("plan-only output missing plan jobs")
	}

	// Should be valid YAML with terraci header
	if !strings.Contains(output, "Generated by terraci") {
		t.Error("missing terraci header")
	}
}

func TestGenerate_DryRun(t *testing.T) {
	dir := fixtureDir(t, "basic")

	// dry-run should succeed without error (output goes to log, not stdout)
	err := runTerraCi(t, dir, "generate", "--dry-run")
	if err != nil {
		t.Fatalf("generate --dry-run failed: %v", err)
	}
}

func TestGenerate_OutputToStdout(t *testing.T) {
	dir := fixtureDir(t, "basic")

	output, err := captureTerraCi(t, dir, "generate")
	if err != nil {
		t.Fatalf("generate (stdout) failed: %v", err)
	}

	if !strings.Contains(output, "Generated by terraci") {
		t.Error("stdout output missing terraci header")
	}
}
