package domain

import (
	"strings"
	"testing"
)

func TestNewJobValidatesRequiredFields(t *testing.T) {
	if _, err := NewJob(JobOptions{Steps: []Step{NewStep(StepOptions{Name: "Checkout", Uses: "actions/checkout@v4"})}}); err == nil {
		t.Fatal("NewJob() error = nil, want missing runs-on error")
	}
	if _, err := NewJob(JobOptions{RunsOn: "ubuntu-latest"}); err == nil {
		t.Fatal("NewJob() error = nil, want missing steps error")
	}
}

func TestWorkflowGettersReturnDefensiveCopies(t *testing.T) {
	step := NewStep(StepOptions{
		Name: "Plan",
		Run:  "terraform plan",
		Env:  map[string]string{"STEP": "true"},
	})
	job, err := NewJob(JobOptions{
		Name:   "plan-vpc",
		RunsOn: "ubuntu-latest",
		Needs:  []string{"setup"},
		Env:    map[string]string{"TF_MODULE": "vpc"},
		Steps:  []Step{step},
	})
	if err != nil {
		t.Fatal(err)
	}
	workflow, err := NewWorkflow(WorkflowOptions{
		Name: "Terraform",
		Env:  map[string]string{"GLOBAL": "true"},
		Jobs: []NamedJob{{Name: "plan-vpc", Job: job}},
	})
	if err != nil {
		t.Fatal(err)
	}

	got, ok := workflow.Job("plan-vpc")
	if !ok {
		t.Fatal("plan-vpc job not found")
	}
	needs := got.Needs()
	needs[0] = "changed"
	if !got.HasNeed("setup") {
		t.Fatalf("Job.Needs() leaked mutation: %#v", got.Needs())
	}
	env := got.Env()
	env["TF_MODULE"] = "changed"
	if got.Env()["TF_MODULE"] != "vpc" {
		t.Fatalf("Job.Env() leaked mutation: %#v", got.Env())
	}
	steps := got.Steps()
	stepEnv := steps[0].Env()
	stepEnv["STEP"] = "changed"
	if got.Steps()[0].Env()["STEP"] != "true" {
		t.Fatalf("Step.Env() leaked mutation: %#v", got.Steps()[0].Env())
	}
	workflowEnv := workflow.Env()
	workflowEnv["GLOBAL"] = "changed"
	if workflow.Env()["GLOBAL"] != "true" {
		t.Fatalf("Workflow.Env() leaked mutation: %#v", workflow.Env())
	}
}

func TestWorkflowToYAMLUsesGeneratedHeader(t *testing.T) {
	step := NewStep(StepOptions{Name: "Checkout", Uses: "actions/checkout@v4"})
	job, err := NewJob(JobOptions{RunsOn: "ubuntu-latest", Steps: []Step{step}})
	if err != nil {
		t.Fatal(err)
	}
	workflow, err := NewWorkflow(WorkflowOptions{Name: "Terraform", Jobs: []NamedJob{{Name: "plan-vpc", Job: job}}})
	if err != nil {
		t.Fatal(err)
	}
	out, err := workflow.ToYAML()
	if err != nil {
		t.Fatalf("ToYAML() error = %v", err)
	}
	if !strings.HasPrefix(string(out), "# Generated by terraci") {
		t.Fatalf("ToYAML() missing generated header:\n%s", string(out))
	}
}

func TestWorkflowBuilderValidatesDuplicateJobs(t *testing.T) {
	step := NewStep(StepOptions{Name: "Checkout", Uses: "actions/checkout@v4"})
	job, err := NewJob(JobOptions{RunsOn: "ubuntu-latest", Steps: []Step{step}})
	if err != nil {
		t.Fatal(err)
	}
	builder := NewWorkflowBuilder(WorkflowOptions{})
	if err := builder.AddJob("test", job); err != nil {
		t.Fatalf("AddJob() error = %v", err)
	}
	if err := builder.AddJob("test", job); err == nil {
		t.Fatal("AddJob() error = nil, want duplicate job error")
	}
}
