package domain

import (
	"strings"
	"testing"
)

func TestWorkflowToYAMLUsesGeneratedHeader(t *testing.T) {
	step := NewStep(StepOptions{Name: "Checkout", Uses: "actions/checkout@v4"})
	job, err := NewJob(JobOptions{RunsOn: "ubuntu-latest", Steps: []Step{step}})
	if err != nil {
		t.Fatal(err)
	}
	builder := NewWorkflowBuilder(WorkflowOptions{Name: "Terraform"})
	mustAddWorkflowJob(t, builder, "plan-vpc", job)
	workflow := mustBuildWorkflow(t, builder)
	out, err := workflow.ToYAML()
	if err != nil {
		t.Fatalf("ToYAML() error = %v", err)
	}
	if !strings.HasPrefix(string(out), "# Generated by terraci") {
		t.Fatalf("ToYAML() missing generated header:\n%s", string(out))
	}
}
