package domain

import (
	"fmt"

	"go.yaml.in/yaml/v4"
)

func (w *Workflow) ToYAML() ([]byte, error) {
	type workflowYAML struct {
		Name        string            `yaml:"name"`
		On          WorkflowTrigger   `yaml:"on"`
		Permissions map[string]string `yaml:"permissions,omitempty"`
		Env         map[string]string `yaml:"env,omitempty"`
		Concurrency *Concurrency      `yaml:"concurrency,omitempty"`
		Jobs        map[string]Job    `yaml:"jobs"`
	}
	payload := workflowYAML{Jobs: map[string]Job{}}
	if w != nil {
		payload.Name = w.name
		payload.On = cloneWorkflowTrigger(w.on)
		payload.Permissions = cloneStringMap(w.permissions)
		payload.Env = cloneStringMap(w.env)
		payload.Concurrency = cloneConcurrency(w.concurrency)
		for name := range w.jobs {
			job := w.jobs[name]
			payload.Jobs[name] = job.clone()
		}
	}
	data, err := yaml.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal workflow: %w", err)
	}

	header := []byte("# Generated by terraci — do not edit\n")
	return append(header, data...), nil
}

func (j Job) MarshalYAML() (any, error) {
	return struct {
		Name        string            `yaml:"name,omitempty"`
		RunsOn      string            `yaml:"runs-on"`
		Container   *Container        `yaml:"container,omitempty"`
		Needs       []string          `yaml:"needs,omitempty"`
		If          string            `yaml:"if,omitempty"`
		Environment string            `yaml:"environment,omitempty"`
		Concurrency *Concurrency      `yaml:"concurrency,omitempty"`
		Env         map[string]string `yaml:"env,omitempty"`
		Steps       []Step            `yaml:"steps"`
	}{
		Name:        j.name,
		RunsOn:      j.runsOn,
		Container:   cloneContainer(j.container),
		Needs:       append([]string(nil), j.needs...),
		If:          j.ifExpr,
		Environment: j.environment,
		Concurrency: cloneConcurrency(j.concurrency),
		Env:         cloneStringMap(j.env),
		Steps:       cloneSteps(j.steps),
	}, nil
}

func (s Step) MarshalYAML() (any, error) {
	return struct {
		Name            string            `yaml:"name,omitempty"`
		Uses            string            `yaml:"uses,omitempty"`
		With            map[string]string `yaml:"with,omitempty"`
		Run             string            `yaml:"run,omitempty"`
		Env             map[string]string `yaml:"env,omitempty"`
		If              string            `yaml:"if,omitempty"`
		ContinueOnError bool              `yaml:"continue-on-error,omitempty"`
	}{
		Name:            s.name,
		Uses:            s.uses,
		With:            cloneStringMap(s.with),
		Run:             s.run,
		Env:             cloneStringMap(s.env),
		If:              s.ifExpr,
		ContinueOnError: s.continueOnError,
	}, nil
}
