# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: terraci

gomod:
  proxy: true

# Generate shell completions and man pages before build
# https://goreleaser.com/customization/hooks/
before:
  hooks:
    - go mod tidy
    - ./scripts/generate-completions.sh
    - ./scripts/generate-manpages.sh

builds:
  - id: terraci
    main: ./cmd/terraci
    binary: terraci
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # ensures mod timestamp to be the commit timestamp
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.CommitDate}}

universal_binaries:
  - replace: true

# config the archives filenames, format, and other options.
# https://goreleaser.com/customization/archive
archives:
  - files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*
    format_overrides:
      - goos: windows
        formats: [zip]

homebrew_casks:
  - repository:
      owner: edelwud
      name: homebrew-tap
    homepage: "https://edelwud.github.io/{{ .ProjectName }}/"
    url:
      verified: "github.com/edelwud/{{ .ProjectName }}"
    manpages:
      - "manpages/{{ .ProjectName }}.1"
      - "manpages/{{ .ProjectName }}-*.1"
    completions:
      bash: "completions/{{ .ProjectName }}.bash"
      zsh: "completions/_{{ .ProjectName }}"
      fish: "completions/{{ .ProjectName }}.fish"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/terraci"]
          end

# creates SBOMs of all archives and the source tarball using syft
# https://goreleaser.com/customization/sbom
sboms:
  - artifacts: archive
  - id: source # Two different sbom configurations need two different IDs
    artifacts: source

checksum:
  name_template: "checksums.txt"

# signs the checksum file
# all files (including the sboms) are included in the checksum, so we don't need to sign each one if we don't want to
# https://goreleaser.com/customization/sign
signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^test:"
      - "^chore"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 300
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: "Documentation updates"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other
      order: 9999

# create multi-arch docker image using dockers_v2
# https://goreleaser.com/customization/dockers_v2/
dockers_v2:
  - id: terraci
    ids:
      - terraci
    images:
      - "ghcr.io/edelwud/terraci"
    tags:
      - "{{ .Tag }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    dockerfile: Dockerfile
    platforms:
      - linux/amd64
      - linux/arm64
    sbom: true
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.name: "{{.ProjectName}}"
      org.opencontainers.image.description: "CLI tool for analyzing Terraform projects and generating GitLab CI pipelines"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"

# signs our docker image
# https://goreleaser.com/customization/docker_sign
docker_signs:
  - cmd: cosign
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes"

# Release to GitHub
release:
  draft: false
  prerelease: auto
  name_template: "{{ .ProjectName }} v{{ .Version }}"
