# yaml-language-server: $schema=https://raw.githubusercontent.com/edelwud/terraci/main/terraci.schema.json

# TerraCi Configuration Example
# Copy this to .terraci.yaml and customize for your project

# Directory structure pattern
structure:
  # Pattern describing your module directory layout
  # Supported placeholders: {service}, {environment}, {region}, {module}
  pattern: "{service}/{environment}/{region}/{module}"
  # Depth is auto-calculated from pattern (4 in this case)
  # depth: 4

# Modules to exclude (glob patterns)
exclude:
  - "*/test/*"
  - "*/sandbox/*"
  # Example: exclude specific region
  # - "platform/*/eu-north-1/*"

# Modules to include (if empty, all are included)
# include:
#   - "platform/*/*/*"

# Library/shared modules configuration
# These are non-executable modules (without provider blocks) that are used by other modules
# When a library module changes, all modules using it will be included in the pipeline
# library_modules:
#   paths:
#     - "_modules"
#     - "shared/modules"

# GitLab CI configuration
gitlab:
  # Terraform/OpenTofu binary to use (terraform, tofu)
  terraform_binary: "terraform"

  # Docker image for terraform jobs (in default section)
  # String format:
  image: "hashicorp/terraform:1.6"
  # Object format (for images requiring entrypoint override):
  # image:
  #   name: "ghcr.io/opentofu/opentofu:1.9-minimal"
  #   entrypoint: [""]

  # For OpenTofu:
  # terraform_binary: "tofu"
  # image: "ghcr.io/opentofu/opentofu:1.6"

  # Prefix for stage names (produces: deploy-plan-0, deploy-apply-0, etc.)
  stages_prefix: "deploy"

  # Maximum parallel jobs per stage
  parallelism: 5

  # Enable terraform plan stage
  plan_enabled: true

  # Auto-approve applies (skip manual confirmation)
  auto_approve: false

  # Enable caching of .terraform directory (providers and modules)
  # Speeds up pipeline execution by reusing downloaded dependencies
  cache_enabled: true

  # Automatically run terraform init after cd to module directory
  init_enabled: true

  # Pipeline variables (global)
  variables:
    TF_IN_AUTOMATION: "true"
    TF_INPUT: "false"

  # Workflow rules for conditional pipeline execution
  # rules:
  #   - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  #     when: always
  #   - if: '$CI_COMMIT_BRANCH == "main"'
  #     when: always
  #   - when: never

  # Default settings applied to all jobs
  job_defaults:
    # GitLab runner tags
    tags:
      - terraform
      - docker
    # Commands to run before each job
    before_script:
      - aws sts get-caller-identity
    # Commands to run after each job (optional)
    # after_script:
    #   - echo "Job completed"
    # Artifacts configuration
    # artifacts:
    #   paths:
    #     - "*.tfplan"
    #   expire_in: "1 day"
    # OIDC tokens for cloud provider authentication (AWS, GCP, Azure)
    # id_tokens:
    #   AWS_OIDC_TOKEN:
    #     aud: "https://gitlab.example.com"
    # Secrets from external secret managers (HashiCorp Vault)
    # secrets:
    #   credentials:
    #     vault: ci/terraform/gitlab-terraform/credentials@namespace
    #     file: true

  # Job-level overrides for plan or apply jobs
  # overwrites:
  #   - type: apply
  #     tags:
  #       - production
  #       - secure
  #     rules:
  #       - if: '$CI_COMMIT_BRANCH == "main"'
  #         when: manual

# Backend configuration (for state path resolution)
backend:
  type: s3
  bucket: my-terraform-state
  region: eu-central-1
  # Pattern for state file keys
  key_pattern: "{service}/{environment}/{region}/{module}/terraform.tfstate"
