package ci

import (
	"fmt"
	"sort"
	"strings"
)

const (
	// maxErrorLength is the maximum length for error messages in summary
	maxErrorLength = 50
	// maxDetailsLength is the maximum length for expandable details
	maxDetailsLength = 10000
	// Cost formatting thresholds
	minCostThreshold      = 0.01
	thousandCostThreshold = 1000
	// shortSHALength is the number of characters to show for abbreviated commit SHAs
	shortSHALength = 8
)

// CommentRenderer renders PR/MR comments
type CommentRenderer struct{}

// NewCommentRenderer creates a new comment renderer
func NewCommentRenderer() *CommentRenderer {
	return &CommentRenderer{}
}

// Render generates the comment body
func (r *CommentRenderer) Render(data *CommentData) string {
	var sb strings.Builder

	// Marker for identifying our comments
	sb.WriteString(CommentMarker)
	sb.WriteString("\n\n")

	// Header
	sb.WriteString("## 🏗️ Terraform Plan Summary\n\n")

	// Stats summary
	stats := r.calculateStats(data.Plans)
	sb.WriteString(r.renderStats(stats))
	sb.WriteString("\n\n")

	// Policy check section (if available)
	if data.PolicySummary != nil {
		sb.WriteString(r.renderPolicySection(data.PolicySummary))
		sb.WriteString("\n")
	}

	// Group plans by environment
	byEnv := r.groupByEnvironment(data.Plans)

	// Render each environment
	envOrder := r.sortedKeys(byEnv)
	for _, env := range envOrder {
		plans := byEnv[env]
		sb.WriteString(r.renderEnvironmentSection(env, plans))
		sb.WriteString("\n")
	}

	// Footer
	sb.WriteString("\n---\n")
	fmt.Fprintf(&sb, "📋 Generated by [terraci](https://github.com/edelwud/terraci) at %s",
		data.GeneratedAt.Format("2006-01-02 15:04:05 UTC"))

	if data.PipelineURL != "" {
		fmt.Fprintf(&sb, " | [Pipeline #%s](%s)", data.PipelineID, data.PipelineURL)
	}

	if data.CommitSHA != "" {
		sha := data.CommitSHA
		if len(sha) > shortSHALength {
			sha = sha[:shortSHALength]
		}
		fmt.Fprintf(&sb, " | Commit: `%s`", sha)
	}

	sb.WriteString("\n")

	return sb.String()
}

// renderPolicySection renders the policy check results section
func (r *CommentRenderer) renderPolicySection(summary *PolicySummary) string {
	var sb strings.Builder

	icon := "✅"
	if summary.HasFailures() {
		icon = "❌"
	} else if summary.HasWarnings() {
		icon = "⚠️"
	}

	fmt.Fprintf(&sb, "### %s Policy Check\n\n", icon)

	var parts []string
	if summary.PassedModules > 0 {
		parts = append(parts, fmt.Sprintf("✅ **%d** passed", summary.PassedModules))
	}
	if summary.WarnedModules > 0 {
		parts = append(parts, fmt.Sprintf("⚠️ **%d** warned", summary.WarnedModules))
	}
	if summary.FailedModules > 0 {
		parts = append(parts, fmt.Sprintf("❌ **%d** failed", summary.FailedModules))
	}

	if len(parts) > 0 {
		fmt.Fprintf(&sb, "**%d** modules checked: %s\n\n", summary.TotalModules, strings.Join(parts, " | "))
	}

	if summary.TotalFailures > 0 {
		sb.WriteString("<details>\n")
		fmt.Fprintf(&sb, "<summary>❌ Failures (%d)</summary>\n\n", summary.TotalFailures)

		for _, result := range summary.Results {
			if len(result.Failures) == 0 {
				continue
			}
			fmt.Fprintf(&sb, "**%s:**\n", result.Module)
			for _, f := range result.Failures {
				fmt.Fprintf(&sb, "- `%s`: %s\n", f.Namespace, f.Message)
			}
			sb.WriteString("\n")
		}

		sb.WriteString("</details>\n\n")
	}

	if summary.TotalWarnings > 0 {
		sb.WriteString("<details>\n")
		fmt.Fprintf(&sb, "<summary>⚠️ Warnings (%d)</summary>\n\n", summary.TotalWarnings)

		for _, result := range summary.Results {
			if len(result.Warnings) == 0 {
				continue
			}
			fmt.Fprintf(&sb, "**%s:**\n", result.Module)
			for _, w := range result.Warnings {
				fmt.Fprintf(&sb, "- `%s`: %s\n", w.Namespace, w.Message)
			}
			sb.WriteString("\n")
		}

		sb.WriteString("</details>\n\n")
	}

	return sb.String()
}

type planStats struct {
	Total     int
	Success   int
	NoChanges int
	Changes   int
	Failed    int
	Pending   int
	Running   int
}

func (r *CommentRenderer) calculateStats(plans []ModulePlan) planStats {
	var stats planStats
	stats.Total = len(plans)

	for i := range plans {
		switch plans[i].Status {
		case PlanStatusSuccess, PlanStatusNoChanges:
			stats.NoChanges++
		case PlanStatusChanges:
			stats.Changes++
		case PlanStatusFailed:
			stats.Failed++
		case PlanStatusPending:
			stats.Pending++
		case PlanStatusRunning:
			stats.Running++
		}
	}
	stats.Success = stats.NoChanges + stats.Changes

	return stats
}

func (r *CommentRenderer) renderStats(stats planStats) string {
	var parts []string

	if stats.Changes > 0 {
		parts = append(parts, fmt.Sprintf("🔄 **%d** with changes", stats.Changes))
	}
	if stats.NoChanges > 0 {
		parts = append(parts, fmt.Sprintf("✅ **%d** no changes", stats.NoChanges))
	}
	if stats.Failed > 0 {
		parts = append(parts, fmt.Sprintf("❌ **%d** failed", stats.Failed))
	}
	if stats.Running > 0 {
		parts = append(parts, fmt.Sprintf("🔄 **%d** running", stats.Running))
	}
	if stats.Pending > 0 {
		parts = append(parts, fmt.Sprintf("⏳ **%d** pending", stats.Pending))
	}

	if len(parts) == 0 {
		return fmt.Sprintf("**%d** modules analyzed", stats.Total)
	}

	return fmt.Sprintf("**%d** modules: %s", stats.Total, strings.Join(parts, " | "))
}

func (r *CommentRenderer) groupByEnvironment(plans []ModulePlan) map[string][]ModulePlan {
	result := make(map[string][]ModulePlan)
	for i := range plans {
		env := plans[i].Get("environment")
		if env == "" {
			env = "default"
		}
		result[env] = append(result[env], plans[i])
	}
	return result
}

func (r *CommentRenderer) sortedKeys(m map[string][]ModulePlan) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func (r *CommentRenderer) renderEnvironmentSection(env string, plans []ModulePlan) string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "### 📦 Environment: `%s`\n\n", env)

	sort.Slice(plans, func(i, j int) bool {
		return plans[i].ModuleID < plans[j].ModuleID
	})

	hasCostData := false
	for i := range plans {
		if plans[i].HasCost {
			hasCostData = true
			break
		}
	}

	if hasCostData {
		sb.WriteString("| Status | Module | Summary | Cost |\n")
		sb.WriteString("|:------:|--------|--------|------|\n")
	} else {
		sb.WriteString("| Status | Module | Summary |\n")
		sb.WriteString("|:------:|--------|--------|\n")
	}

	for i := range plans {
		sb.WriteString(r.renderPlanRow(&plans[i], hasCostData))
	}

	for i := range plans {
		hasDetails := plans[i].StructuredDetails != "" || plans[i].RawPlanOutput != "" || plans[i].Error != ""
		if hasDetails && (plans[i].Status == PlanStatusChanges || plans[i].Status == PlanStatusFailed) {
			sb.WriteString(r.renderExpandableDetails(&plans[i]))
		}
	}

	return sb.String()
}

func (r *CommentRenderer) renderPlanRow(p *ModulePlan, includeCost bool) string {
	status := r.statusIcon(p.Status)
	module := fmt.Sprintf("`%s`", p.ModuleID)

	summary := p.Summary
	if p.Error != "" {
		summary = fmt.Sprintf("⚠️ %s", Truncate(p.Error, maxErrorLength))
	}
	if summary == "" {
		summary = "-"
	}

	if !includeCost {
		return fmt.Sprintf("| %s | %s | %s |\n", status, module, summary)
	}

	cost := FormatCostCell(p)
	return fmt.Sprintf("| %s | %s | %s | %s |\n", status, module, summary, cost)
}

// FormatCostCell formats the cost cell for a module plan
func FormatCostCell(p *ModulePlan) string {
	if !p.HasCost {
		return "-"
	}

	if p.CostDiff == 0 {
		return FormatMonthlyCost(p.CostAfter)
	}

	before := FormatMonthlyCost(p.CostBefore)
	after := FormatMonthlyCost(p.CostAfter)
	diff := FormatCostDiff(p.CostDiff)

	return fmt.Sprintf("%s %s → %s", before, diff, after)
}

// FormatMonthlyCost formats a monthly cost value
func FormatMonthlyCost(cost float64) string {
	if cost == 0 {
		return "$0"
	}
	if cost < minCostThreshold {
		return "<$0.01"
	}
	if cost >= thousandCostThreshold {
		return fmt.Sprintf("$%.0f", cost)
	}
	if cost >= 1 {
		return fmt.Sprintf("$%.2f", cost)
	}
	return fmt.Sprintf("$%.4f", cost)
}

// FormatCostDiff formats a cost difference with sign
func FormatCostDiff(diff float64) string {
	if diff == 0 {
		return "$0"
	}
	if diff > 0 {
		if diff >= thousandCostThreshold {
			return fmt.Sprintf("+$%.0f", diff)
		}
		if diff >= 1 {
			return fmt.Sprintf("+$%.2f", diff)
		}
		return fmt.Sprintf("+$%.4f", diff)
	}
	diff = -diff
	if diff >= thousandCostThreshold {
		return fmt.Sprintf("-$%.0f", diff)
	}
	if diff >= 1 {
		return fmt.Sprintf("-$%.2f", diff)
	}
	return fmt.Sprintf("-$%.4f", diff)
}

func (r *CommentRenderer) statusIcon(status PlanStatus) string {
	switch status {
	case PlanStatusSuccess, PlanStatusNoChanges:
		return "✅"
	case PlanStatusChanges:
		return "🔄"
	case PlanStatusFailed:
		return "❌"
	case PlanStatusPending:
		return "⏳"
	case PlanStatusRunning:
		return "🔄"
	default:
		return "❓"
	}
}

func (r *CommentRenderer) renderExpandableDetails(p *ModulePlan) string {
	var sb strings.Builder

	title := fmt.Sprintf("📋 %s", p.ModuleID)
	if p.Summary != "" && p.Summary != "No changes" {
		title = fmt.Sprintf("📋 %s (%s)", p.ModuleID, p.Summary)
	}
	if p.Status == PlanStatusFailed {
		title = fmt.Sprintf("❌ %s", p.ModuleID)
	}

	fmt.Fprintf(&sb, "\n<details>\n<summary>%s</summary>\n\n", title)

	if p.StructuredDetails != "" {
		sb.WriteString(p.StructuredDetails)
		sb.WriteString("\n\n")
	}

	if p.RawPlanOutput != "" {
		sb.WriteString("<details>\n<summary>Full plan output</summary>\n\n")
		sb.WriteString("```diff\n")
		sb.WriteString(Truncate(p.RawPlanOutput, maxDetailsLength))
		sb.WriteString("\n```\n")
		sb.WriteString("</details>\n")
	}

	sb.WriteString("</details>\n")

	return sb.String()
}

// Truncate truncates a string to maxLen characters
func Truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}
