package summaryengine

import (
	"fmt"
	"strings"
	"time"

	"github.com/edelwud/terraci/pkg/ci"
	"github.com/edelwud/terraci/plugins/internal/reportrender"
)

const (
	maxErrorLength   = 50
	maxDetailsLength = 10000
	shortSHALength   = 8
	noChangesSummary = "No changes"
	columnModule     = "Module"
)

// CommentMarker is used to identify terraci comments for updates.
const CommentMarker = ci.CommentMarker

func encodeRenderSection(title, sectionSummary string, status ci.ReportStatus, blocks ...ci.RenderBlock) (ci.ReportSection, error) {
	section, err := ci.NewRenderedSection(ci.RenderedSectionOptions{
		Title:   title,
		Summary: sectionSummary,
		Status:  status,
		Blocks:  blocks,
	})
	if err != nil {
		return ci.ReportSection{}, fmt.Errorf("encode rendered section: %w", err)
	}
	return section, nil
}

// ComposeComment builds the final markdown comment from plans and typed plugin reports.
func ComposeComment(plans []ci.PlanResult, reports []*ci.Report, commitSHA, pipelineID string, generatedAt time.Time) (string, error) {
	return ComposeCommentWithOptions(plans, reports, commitSHA, pipelineID, generatedAt, true)
}

// ComposeCommentWithOptions builds the final markdown comment with explicit rendering options.
func ComposeCommentWithOptions(plans []ci.PlanResult, reports []*ci.Report, commitSHA, pipelineID string, generatedAt time.Time, includeDetails bool) (string, error) {
	sections, err := BuildSummarySectionsWithOptions(plans, reports, includeDetails)
	if err != nil {
		return "", err
	}

	var sb strings.Builder
	sb.WriteString(ci.CommentMarker)
	sb.WriteString("\n\n")
	sb.WriteString("## Terraform Plan Summary\n\n")

	for _, section := range sections {
		rendered, err := reportrender.MarkdownSection(section)
		if err != nil {
			return "", fmt.Errorf("render summary section %q: %w", sectionTitle(section), err)
		}
		if rendered == "" {
			continue
		}
		sb.WriteString(rendered)
		sb.WriteString("\n\n")
	}

	sb.WriteString("---\n")
	fmt.Fprintf(&sb, "Generated by [terraci](https://github.com/edelwud/terraci) at %s", generatedAt.Format("2006-01-02 15:04:05 UTC"))
	if pipelineID != "" {
		fmt.Fprintf(&sb, " | Pipeline #%s", pipelineID)
	}
	if commitSHA != "" {
		sha := commitSHA
		if len(sha) > shortSHALength {
			sha = sha[:shortSHALength]
		}
		fmt.Fprintf(&sb, " | Commit: `%s`", sha)
	}
	sb.WriteString("\n")

	return sb.String(), nil
}
