package generate

import (
	"strings"
	"testing"

	"github.com/edelwud/terraci/pkg/discovery"
	"github.com/edelwud/terraci/pkg/pipeline"
	domainpkg "github.com/edelwud/terraci/plugins/github/internal/domain"
)

func TestJobName(t *testing.T) {
	tests := []struct {
		name     string
		module   *discovery.Module
		jobType  string
		expected string
	}{
		{name: "plan job for vpc", module: createTestModule("platform", "stage", "eu-central-1", "vpc"), jobType: "plan", expected: "plan-platform-stage-eu-central-1-vpc"},
		{name: "apply job for eks", module: createTestModule("platform", "prod", "us-west-2", "eks"), jobType: "apply", expected: "apply-platform-prod-us-west-2-eks"},
		{name: "plan job with different service", module: createTestModule("data", "dev", "ap-southeast-1", "rds"), jobType: "plan", expected: "plan-data-dev-ap-southeast-1-rds"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := pipeline.JobName(tt.jobType, tt.module)
			if result != tt.expected {
				t.Errorf("jobName(%s, %s) = %s, expected %s", tt.module.ID(), tt.jobType, result, tt.expected)
			}
		})
	}
}

func TestToYAML(t *testing.T) {
	workflow := &domainpkg.Workflow{
		Name: "Terraform",
		On: domainpkg.WorkflowTrigger{
			Push: &domainpkg.PushTrigger{Branches: []string{"main"}},
		},
		Env: map[string]string{"TERRAFORM_BINARY": "terraform"},
		Jobs: map[string]*domainpkg.Job{
			"plan-test": {
				RunsOn: "ubuntu-latest",
				Steps: []domainpkg.Step{
					{Name: "Checkout", Uses: "actions/checkout@v4"},
					{Name: "Plan", Run: "terraform plan"},
				},
			},
		},
	}

	yamlBytes, err := workflow.ToYAML()
	if err != nil {
		t.Fatalf("ToYAML failed: %v", err)
	}

	yaml := string(yamlBytes)
	checks := []struct {
		desc     string
		contains string
	}{
		{"generated header", "Generated by terraci"},
		{"name field", "name:"},
		{"jobs field", "jobs:"},
		{"plan-test job", "plan-test:"},
		{"TERRAFORM_BINARY", "TERRAFORM_BINARY"},
	}
	for _, check := range checks {
		if !strings.Contains(yaml, check.contains) {
			t.Errorf("YAML should contain %s (%q)", check.desc, check.contains)
		}
	}
}
