package generate

import (
	"strings"
	"testing"

	domainpkg "github.com/edelwud/terraci/plugins/github/internal/domain"
)

func TestToYAML(t *testing.T) {
	workflow := &domainpkg.Workflow{
		Name: "Terraform",
		On: domainpkg.WorkflowTrigger{
			Push: &domainpkg.PushTrigger{Branches: []string{"main"}},
		},
		Env: map[string]string{"TERRAFORM_BINARY": "terraform"},
		Jobs: map[string]*domainpkg.Job{
			"plan-test": {
				RunsOn: "ubuntu-latest",
				Steps: []domainpkg.Step{
					{Name: "Checkout", Uses: "actions/checkout@v4"},
					{Name: "Plan", Run: "terraform plan"},
				},
			},
		},
	}

	yamlBytes, err := workflow.ToYAML()
	if err != nil {
		t.Fatalf("ToYAML failed: %v", err)
	}

	yaml := string(yamlBytes)
	checks := []struct {
		desc     string
		contains string
	}{
		{"generated header", "Generated by terraci"},
		{"name field", "name:"},
		{"jobs field", "jobs:"},
		{"plan-test job", "plan-test:"},
		{"TERRAFORM_BINARY", "TERRAFORM_BINARY"},
	}
	for _, check := range checks {
		if !strings.Contains(yaml, check.contains) {
			t.Errorf("YAML should contain %s (%q)", check.desc, check.contains)
		}
	}
}
