package generate

import (
	"strings"
	"testing"

	domainpkg "github.com/edelwud/terraci/plugins/github/internal/domain"
)

func TestToYAML(t *testing.T) {
	job, err := domainpkg.NewJob(domainpkg.JobOptions{
		RunsOn: "ubuntu-latest",
		Steps: []domainpkg.Step{
			domainpkg.NewStep(domainpkg.StepOptions{Name: "Checkout", Uses: "actions/checkout@v4"}),
			domainpkg.NewStep(domainpkg.StepOptions{Name: "Plan", Run: "terraform plan"}),
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	workflow, err := domainpkg.NewWorkflow(domainpkg.WorkflowOptions{
		Name: "Terraform",
		On: domainpkg.WorkflowTrigger{
			Push: &domainpkg.PushTrigger{Branches: []string{"main"}},
		},
		Env:  map[string]string{"TERRAFORM_BINARY": "terraform"},
		Jobs: []domainpkg.NamedJob{{Name: "plan-test", Job: job}},
	})
	if err != nil {
		t.Fatal(err)
	}

	yamlBytes, err := workflow.ToYAML()
	if err != nil {
		t.Fatalf("ToYAML failed: %v", err)
	}

	yaml := string(yamlBytes)
	checks := []struct {
		desc     string
		contains string
	}{
		{"generated header", "Generated by terraci"},
		{"name field", "name:"},
		{"jobs field", "jobs:"},
		{"plan-test job", "plan-test:"},
		{"TERRAFORM_BINARY", "TERRAFORM_BINARY"},
	}
	for _, check := range checks {
		if !strings.Contains(yaml, check.contains) {
			t.Errorf("YAML should contain %s (%q)", check.desc, check.contains)
		}
	}
}
