package cmd

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"

	log "github.com/caarlos0/log"

	"github.com/edelwud/terraci/cmd/terraci/internal/generateflow"
	"github.com/edelwud/terraci/cmd/terraci/internal/projectflow"
	"github.com/edelwud/terraci/cmd/terraci/internal/runflow"
	"github.com/edelwud/terraci/pkg/filter"
	"github.com/edelwud/terraci/pkg/pipeline"
)

func newGenerateCmd() *cobra.Command {
	var (
		outputFile  string
		changedOnly bool
		baseRef     string
		dryRun      bool
		dryRunFmt   string
		planOnly    bool
	)
	ff := &filter.Flags{}

	cmd := &cobra.Command{
		Use:   "generate",
		Short: "Generate CI pipeline",
		Long: `Generate a CI pipeline YAML file based on the Terraform
module structure and dependencies.

Examples:
  terraci generate -o .gitlab-ci.yml
  terraci generate --changed-only --base-ref main
	  terraci generate --exclude "*/test/*"
	  terraci generate --filter environment=stage --filter environment=prod
	  terraci generate --dry-run
	  terraci generate --plan-only`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			prepared, err := runflow.FromContext(cmd.Context())
			if err != nil {
				return err
			}
			result, err := generateflow.Run(cmd.Context(), generateflow.NewRuntime(prepared), generateflow.Request{
				Filters:     *ff,
				ChangedOnly: changedOnly,
				BaseRef:     baseRef,
				PlanOnly:    planOnly,
				DryRun:      dryRun,
			})
			if err != nil {
				return err
			}

			logGenerateProjectDiagnostics(result.Project)
			if result.Skipped {
				log.Info("no modules to process")
				return nil
			}

			log.WithField("modules", len(result.Project.Targets)).Info("generating pipeline")
			if dryRun {
				return renderDryRun(result.DryRun, dryRunFmt)
			}

			return writePipelineOutput(result.Pipeline, outputFile)
		},
	}

	cmd.Flags().StringVarP(&outputFile, "output", "o", "", "output file (default: stdout)")
	cmd.Flags().BoolVar(&changedOnly, "changed-only", false, "only include changed modules and their dependents")
	cmd.Flags().StringVar(&baseRef, "base-ref", "", "base git ref for change detection (default: auto-detect)")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "show what would be generated without creating output")
	cmd.Flags().StringVar(&dryRunFmt, "format", "text", "dry-run output format: text or json")
	cmd.Flags().BoolVar(&planOnly, "plan-only", false, "generate only plan jobs (no apply jobs)")
	registerFilterFlags(cmd, ff)

	return cmd
}

func logGenerateProjectDiagnostics(result *projectflow.Result) {
	if result == nil || result.Workflow == nil {
		return
	}
	logExtractionWarnings(result.Workflow.Warnings)
	logLibraryModuleUsage(result.LibraryUsages)
	logCycles(result.Workflow.Graph.DetectCycles())
}

func logExtractionWarnings(errs []error) {
	if len(errs) == 0 {
		return
	}
	log.WithField("count", len(errs)).Warn("warnings during dependency extraction")
	log.IncreasePadding()
	for _, e := range errs {
		log.WithField("warning", e.Error()).Debug("extraction warning")
	}
	log.DecreasePadding()
}

func logLibraryModuleUsage(usages []projectflow.LibraryUsage) {
	if len(usages) == 0 {
		return
	}

	log.WithField("count", len(usages)).Info("library modules detected")
	log.IncreasePadding()
	for _, usage := range usages {
		log.WithField("path", usage.RelativePath).WithField("used_by", usage.UsedBy).Debug("library module")
	}
	log.DecreasePadding()
}

func logCycles(cycles [][]string) {
	if len(cycles) == 0 {
		return
	}
	log.WithField("count", len(cycles)).Warn("circular dependencies detected")
	log.IncreasePadding()
	for _, cycle := range cycles {
		log.WithField("cycle", fmt.Sprintf("%v", cycle)).Warn("cycle found")
	}
	log.DecreasePadding()
}

func renderDryRun(result *pipeline.DryRunResult, format string) error {
	switch format {
	case "json":
		// Machine-readable shape for CI gating: scripts can consume this via
		// `terraci generate --dry-run --format json | jq '.affected_modules > 5'`.
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		return enc.Encode(result)
	case "", "text":
		log.Info("dry run results")
		log.IncreasePadding()
		log.WithField("total", result.TotalModules).Info("modules discovered")
		log.WithField("affected", result.AffectedModules).Info("modules to process")
		log.WithField("stages", result.Stages).Info("pipeline stages")
		log.WithField("jobs", result.Jobs).Info("pipeline jobs")
		log.DecreasePadding()

		log.Info("execution order")
		log.IncreasePadding()
		for i, group := range result.JobGroups {
			log.WithField("group", i).WithField("jobs", fmt.Sprintf("%v", group)).Debug("job group")
		}
		log.DecreasePadding()
		return nil
	default:
		return fmt.Errorf("unsupported dry-run format %q (want text or json)", format)
	}
}

func writePipelineOutput(p pipeline.GeneratedPipeline, outputFile string) error {
	yaml, err := p.ToYAML()
	if err != nil {
		return fmt.Errorf("serialize pipeline: %w", err)
	}

	content := append([]byte("# Generated by terraci\n# DO NOT EDIT - this file is auto-generated\n# https://github.com/edelwud/terraci\n\n"), yaml...)

	if outputFile != "" {
		if err := os.WriteFile(outputFile, content, 0o600); err != nil {
			return fmt.Errorf("write output file: %w", err)
		}
		log.WithField("file", outputFile).Info("pipeline written")
	} else {
		fmt.Print(string(content))
	}

	return nil
}
