package summaryengine

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/edelwud/terraci/pkg/ci"
)

const (
	// maxErrorLength is the maximum length for error messages in summary
	maxErrorLength = 50
	// maxDetailsLength is the maximum length for expandable details
	maxDetailsLength = 10000
	// Cost formatting thresholds
	minCostThreshold      = 0.01
	thousandCostThreshold = 1000
	// shortSHALength is the number of characters to show for abbreviated commit SHAs
	shortSHALength = 8
)

// CommentMarker is used to identify terraci comments for updates
const CommentMarker = ci.CommentMarker

// ComposeComment builds the final markdown comment from plans and plugin reports.
func ComposeComment(plans []ci.ModulePlan, reports []*ci.Report, commitSHA, pipelineID string, generatedAt time.Time) string {
	var sb strings.Builder

	// Marker for identifying our comments
	sb.WriteString(ci.CommentMarker)
	sb.WriteString("\n\n")

	// Header
	sb.WriteString("## Terraform Plan Summary\n\n")

	// Stats summary
	stats := calculateStats(plans)
	sb.WriteString(renderStats(stats))
	sb.WriteString("\n\n")

	// Plugin report sections
	for _, r := range reports {
		sb.WriteString(renderReportSection(r))
		sb.WriteString("\n")
	}

	// Group plans by environment
	byEnv := groupByEnvironment(plans)

	// Render each environment
	envOrder := sortedKeys(byEnv)
	for _, env := range envOrder {
		envPlans := byEnv[env]
		sb.WriteString(renderEnvironmentSection(env, envPlans))
		sb.WriteString("\n")
	}

	// Footer
	sb.WriteString("\n---\n")
	fmt.Fprintf(&sb, "Generated by [terraci](https://github.com/edelwud/terraci) at %s",
		generatedAt.Format("2006-01-02 15:04:05 UTC"))

	if pipelineID != "" {
		fmt.Fprintf(&sb, " | Pipeline #%s", pipelineID)
	}

	if commitSHA != "" {
		sha := commitSHA
		if len(sha) > shortSHALength {
			sha = sha[:shortSHALength]
		}
		fmt.Fprintf(&sb, " | Commit: `%s`", sha)
	}

	sb.WriteString("\n")

	return sb.String()
}

func renderReportSection(r *ci.Report) string {
	var sb strings.Builder

	statusIcon := reportStatusIcon(r.Status)
	fmt.Fprintf(&sb, "### %s %s\n\n", statusIcon, r.Title)
	fmt.Fprintf(&sb, "**Status:** %s — %s\n\n", r.Status, r.Summary)
	if r.Body != "" {
		sb.WriteString(r.Body)
		sb.WriteString("\n")
	}

	return sb.String()
}

func reportStatusIcon(status ci.ReportStatus) string {
	switch status {
	case ci.ReportStatusPass:
		return "pass"
	case ci.ReportStatusWarn:
		return "warn"
	case ci.ReportStatusFail:
		return "fail"
	default:
		return string(status)
	}
}

type planStats struct {
	Total     int
	Success   int
	NoChanges int
	Changes   int
	Failed    int
	Pending   int
	Running   int
}

func calculateStats(plans []ci.ModulePlan) planStats {
	var stats planStats
	stats.Total = len(plans)

	for i := range plans {
		switch plans[i].Status {
		case ci.PlanStatusSuccess, ci.PlanStatusNoChanges:
			stats.NoChanges++
		case ci.PlanStatusChanges:
			stats.Changes++
		case ci.PlanStatusFailed:
			stats.Failed++
		case ci.PlanStatusPending:
			stats.Pending++
		case ci.PlanStatusRunning:
			stats.Running++
		}
	}
	stats.Success = stats.NoChanges + stats.Changes

	return stats
}

func renderStats(stats planStats) string {
	var parts []string

	if stats.Changes > 0 {
		parts = append(parts, fmt.Sprintf("**%d** with changes", stats.Changes))
	}
	if stats.NoChanges > 0 {
		parts = append(parts, fmt.Sprintf("**%d** no changes", stats.NoChanges))
	}
	if stats.Failed > 0 {
		parts = append(parts, fmt.Sprintf("**%d** failed", stats.Failed))
	}
	if stats.Running > 0 {
		parts = append(parts, fmt.Sprintf("**%d** running", stats.Running))
	}
	if stats.Pending > 0 {
		parts = append(parts, fmt.Sprintf("**%d** pending", stats.Pending))
	}

	if len(parts) == 0 {
		return fmt.Sprintf("**%d** modules analyzed", stats.Total)
	}

	return fmt.Sprintf("**%d** modules: %s", stats.Total, strings.Join(parts, " | "))
}

func groupByEnvironment(plans []ci.ModulePlan) map[string][]ci.ModulePlan {
	result := make(map[string][]ci.ModulePlan)
	for i := range plans {
		env := plans[i].Get("environment")
		if env == "" {
			env = "default"
		}
		result[env] = append(result[env], plans[i])
	}
	return result
}

func sortedKeys(m map[string][]ci.ModulePlan) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func renderEnvironmentSection(env string, plans []ci.ModulePlan) string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "### Environment: `%s`\n\n", env)

	sort.Slice(plans, func(i, j int) bool {
		return plans[i].ModuleID < plans[j].ModuleID
	})

	hasCostData := false
	for i := range plans {
		if plans[i].HasCost {
			hasCostData = true
			break
		}
	}

	if hasCostData {
		sb.WriteString("| Status | Module | Summary | Cost |\n")
		sb.WriteString("|:------:|--------|--------|------|\n")
	} else {
		sb.WriteString("| Status | Module | Summary |\n")
		sb.WriteString("|:------:|--------|--------|\n")
	}

	for i := range plans {
		sb.WriteString(renderPlanRow(&plans[i], hasCostData))
	}

	for i := range plans {
		hasDetails := plans[i].StructuredDetails != "" || plans[i].RawPlanOutput != "" || plans[i].Error != ""
		if hasDetails && (plans[i].Status == ci.PlanStatusChanges || plans[i].Status == ci.PlanStatusFailed) {
			sb.WriteString(renderExpandableDetails(&plans[i]))
		}
	}

	return sb.String()
}

func renderPlanRow(p *ci.ModulePlan, includeCost bool) string {
	status := statusIcon(p.Status)
	module := fmt.Sprintf("`%s`", p.ModuleID)

	summary := p.Summary
	if p.Error != "" {
		summary = fmt.Sprintf("err: %s", Truncate(p.Error, maxErrorLength))
	}
	if summary == "" {
		summary = "-"
	}

	if !includeCost {
		return fmt.Sprintf("| %s | %s | %s |\n", status, module, summary)
	}

	cost := FormatCostCell(p)
	return fmt.Sprintf("| %s | %s | %s | %s |\n", status, module, summary, cost)
}

// FormatCostCell formats the cost cell for a module plan
func FormatCostCell(p *ci.ModulePlan) string {
	if !p.HasCost {
		return "-"
	}

	if p.CostDiff == 0 {
		return FormatMonthlyCost(p.CostAfter)
	}

	before := FormatMonthlyCost(p.CostBefore)
	after := FormatMonthlyCost(p.CostAfter)
	diff := FormatCostDiff(p.CostDiff)

	return fmt.Sprintf("%s %s -> %s", before, diff, after)
}

// FormatMonthlyCost formats a monthly cost value
func FormatMonthlyCost(cost float64) string {
	if cost == 0 {
		return "$0"
	}
	if cost < minCostThreshold {
		return "<$0.01"
	}
	if cost >= thousandCostThreshold {
		return fmt.Sprintf("$%.0f", cost)
	}
	if cost >= 1 {
		return fmt.Sprintf("$%.2f", cost)
	}
	return fmt.Sprintf("$%.4f", cost)
}

// FormatCostDiff formats a cost difference with sign
func FormatCostDiff(diff float64) string {
	if diff == 0 {
		return "$0"
	}
	if diff > 0 {
		if diff >= thousandCostThreshold {
			return fmt.Sprintf("+$%.0f", diff)
		}
		if diff >= 1 {
			return fmt.Sprintf("+$%.2f", diff)
		}
		return fmt.Sprintf("+$%.4f", diff)
	}
	diff = -diff
	if diff >= thousandCostThreshold {
		return fmt.Sprintf("-$%.0f", diff)
	}
	if diff >= 1 {
		return fmt.Sprintf("-$%.2f", diff)
	}
	return fmt.Sprintf("-$%.4f", diff)
}

func statusIcon(status ci.PlanStatus) string {
	switch status {
	case ci.PlanStatusSuccess, ci.PlanStatusNoChanges:
		return "ok"
	case ci.PlanStatusChanges:
		return "changes"
	case ci.PlanStatusFailed:
		return "failed"
	case ci.PlanStatusPending:
		return "pending"
	case ci.PlanStatusRunning:
		return "running"
	default:
		return "?"
	}
}

func renderExpandableDetails(p *ci.ModulePlan) string {
	var sb strings.Builder

	title := p.ModuleID
	if p.Summary != "" && p.Summary != "No changes" {
		title = fmt.Sprintf("%s (%s)", p.ModuleID, p.Summary)
	}
	if p.Status == ci.PlanStatusFailed {
		title = fmt.Sprintf("FAILED %s", p.ModuleID)
	}

	fmt.Fprintf(&sb, "\n<details>\n<summary>%s</summary>\n\n", title)

	if p.StructuredDetails != "" {
		sb.WriteString(p.StructuredDetails)
		sb.WriteString("\n\n")
	}

	if p.RawPlanOutput != "" {
		sb.WriteString("<details>\n<summary>Full plan output</summary>\n\n")
		sb.WriteString("```diff\n")
		sb.WriteString(Truncate(p.RawPlanOutput, maxDetailsLength))
		sb.WriteString("\n```\n")
		sb.WriteString("</details>\n")
	}

	sb.WriteString("</details>\n")

	return sb.String()
}

// Truncate truncates a string to maxLen characters
func Truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}
