package summaryengine

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/edelwud/terraci/pkg/ci"
)

const (
	maxErrorLength        = 50
	maxDetailsLength      = 10000
	minCostThreshold      = 0.01
	thousandCostThreshold = 1000
	shortSHALength        = 8
)

// CommentMarker is used to identify terraci comments for updates
const CommentMarker = ci.CommentMarker

// ComposeComment builds the final markdown comment from plans and typed plugin reports.
func ComposeComment(plans []ci.ModulePlan, reports []*ci.Report, commitSHA, pipelineID string, generatedAt time.Time) string {
	return ComposeCommentWithOptions(plans, reports, commitSHA, pipelineID, generatedAt, true)
}

// ComposeCommentWithOptions builds the final markdown comment with explicit rendering options.
func ComposeCommentWithOptions(plans []ci.ModulePlan, reports []*ci.Report, commitSHA, pipelineID string, generatedAt time.Time, includeDetails bool) string {
	sections := BuildSummarySectionsWithOptions(plans, reports, includeDetails)

	var sb strings.Builder
	sb.WriteString(ci.CommentMarker)
	sb.WriteString("\n\n")
	sb.WriteString("## Terraform Plan Summary\n\n")

	for _, section := range sections {
		rendered := renderMarkdownSection(section)
		if rendered == "" {
			continue
		}
		sb.WriteString(rendered)
		sb.WriteString("\n\n")
	}

	sb.WriteString("---\n")
	fmt.Fprintf(&sb, "Generated by [terraci](https://github.com/edelwud/terraci) at %s", generatedAt.Format("2006-01-02 15:04:05 UTC"))
	if pipelineID != "" {
		fmt.Fprintf(&sb, " | Pipeline #%s", pipelineID)
	}
	if commitSHA != "" {
		sha := commitSHA
		if len(sha) > shortSHALength {
			sha = sha[:shortSHALength]
		}
		fmt.Fprintf(&sb, " | Commit: `%s`", sha)
	}
	sb.WriteString("\n")

	return sb.String()
}

// BuildSummarySections builds the filtered summary view from plan results and typed plugin reports.
func BuildSummarySections(plans []ci.ModulePlan, reports []*ci.Report) []ci.ReportSection {
	return BuildSummarySectionsWithOptions(plans, reports, true)
}

// BuildSummarySectionsWithOptions builds the filtered summary view with explicit rendering options.
func BuildSummarySectionsWithOptions(plans []ci.ModulePlan, reports []*ci.Report, includeDetails bool) []ci.ReportSection {
	sections := make([]ci.ReportSection, 0, 1+len(plans)+len(reports))
	sections = append(sections, buildSummaryOverviewSection(plans, reports))
	sections = append(sections, buildTerraformPlanSections(plans, includeDetails)...)
	for _, report := range reports {
		sections = append(sections, filteredReportSections(report)...)
	}
	return sections
}

func buildSummaryOverviewSection(plans []ci.ModulePlan, reports []*ci.Report) ci.ReportSection {
	stats := calculateStats(plans)
	overviews := make([]ci.SummaryReportOverview, 0, len(reports))
	for _, report := range reports {
		if report == nil {
			continue
		}
		for _, section := range report.Sections {
			overviews = append(overviews, ci.SummaryReportOverview{
				Kind:    section.Kind,
				Title:   sectionTitle(section),
				Status:  section.Status,
				Summary: section.SectionSummary,
			})
		}
	}

	return ci.ReportSection{
		Kind:           ci.ReportSectionKindOverview,
		Title:          "Summary",
		Status:         overallSummaryStatus(plans, reports),
		SectionSummary: renderStats(stats),
		Overview: &ci.OverviewSection{
			PlanStats: ci.SummaryPlanStats{
				Total:     stats.Total,
				Success:   stats.Success,
				NoChanges: stats.NoChanges,
				Changes:   stats.Changes,
				Failed:    stats.Failed,
				Pending:   stats.Pending,
				Running:   stats.Running,
			},
			Reports: overviews,
		},
	}
}

func overallSummaryStatus(plans []ci.ModulePlan, reports []*ci.Report) ci.ReportStatus {
	for i := range plans {
		if plans[i].Status == ci.PlanStatusFailed {
			return ci.ReportStatusFail
		}
	}
	for _, report := range reports {
		if report == nil {
			continue
		}
		if report.Status == ci.ReportStatusFail {
			return ci.ReportStatusFail
		}
	}
	for i := range plans {
		if plans[i].Status == ci.PlanStatusChanges {
			return ci.ReportStatusWarn
		}
	}
	for _, report := range reports {
		if report == nil {
			continue
		}
		if report.Status == ci.ReportStatusWarn {
			return ci.ReportStatusWarn
		}
	}
	return ci.ReportStatusPass
}

func buildTerraformPlanSections(plans []ci.ModulePlan, includeDetails bool) []ci.ReportSection {
	byEnv := groupByEnvironment(plans)
	envOrder := sortedKeys(byEnv)
	sections := make([]ci.ReportSection, 0, len(envOrder))
	for _, env := range envOrder {
		envPlans := visibleEnvironmentPlans(byEnv[env])
		if len(envPlans) == 0 {
			continue
		}

		sort.Slice(envPlans, func(i, j int) bool {
			return envPlans[i].ModuleID < envPlans[j].ModuleID
		})

		rows := make([]ci.ModuleTableRow, 0, len(envPlans))
		status := ci.ReportStatusWarn
		for i := range envPlans {
			plan := envPlans[i]
			if plan.Status == ci.PlanStatusFailed {
				status = ci.ReportStatusFail
			}
			rows = append(rows, ci.ModuleTableRow{
				ModuleID:       plan.ModuleID,
				ModulePath:     plan.ModulePath,
				Status:         plan.Status,
				Summary:        plan.Summary,
				Error:          plan.Error,
				EstimateBefore: plan.EstimateBefore,
				EstimateAfter:  plan.EstimateAfter,
				EstimateDiff:   plan.EstimateDiff,
				HasEstimate:    plan.HasEstimate,
			})
			if includeDetails {
				rows[len(rows)-1].StructuredDetails = plan.StructuredDetails
				rows[len(rows)-1].RawPlanOutput = plan.RawPlanOutput
			}
		}

		sections = append(sections, ci.ReportSection{
			Kind:           ci.ReportSectionKindModuleTable,
			Title:          fmt.Sprintf("Environment: `%s`", env),
			Status:         status,
			SectionSummary: fmt.Sprintf("%d actionable modules", len(rows)),
			ModuleTable: &ci.ModuleTableSection{
				Environment: env,
				Rows:        rows,
			},
		})
	}
	return sections
}

func filteredReportSections(report *ci.Report) []ci.ReportSection {
	if report == nil {
		return nil
	}

	sections := make([]ci.ReportSection, 0, len(report.Sections))
	for _, section := range report.Sections {
		filtered, ok := filterReportSection(section)
		if ok {
			sections = append(sections, filtered)
		}
	}
	return sections
}

func renderReportSection(report *ci.Report) string {
	if report == nil {
		return ""
	}

	sections := filteredReportSections(report)
	if len(sections) == 0 {
		return renderSectionHeader(ci.ReportSection{
			Kind:           firstSectionKind(report.Sections),
			Title:          report.Title,
			Status:         report.Status,
			SectionSummary: report.Summary,
		})
	}

	var sb strings.Builder
	for i, section := range sections {
		if i > 0 {
			sb.WriteString("\n\n")
		}
		sb.WriteString(renderMarkdownSection(section))
	}
	return sb.String()
}

func firstSectionKind(sections []ci.ReportSection) ci.ReportSectionKind {
	if len(sections) == 0 {
		return ""
	}
	return sections[0].Kind
}

func filterReportSection(section ci.ReportSection) (ci.ReportSection, bool) {
	switch section.Kind {
	case ci.ReportSectionKindEstimateChanges:
		if section.EstimateChanges == nil {
			return ci.ReportSection{}, false
		}
		rows := make([]ci.EstimateChangeRow, 0, len(section.EstimateChanges.Rows))
		for _, row := range section.EstimateChanges.Rows {
			if row.Diff > 0 {
				rows = append(rows, row)
			}
		}
		if len(rows) == 0 {
			return ci.ReportSection{}, false
		}
		section.EstimateChanges = &ci.EstimateChangesSection{Totals: section.EstimateChanges.Totals, Rows: rows}
		return section, true
	case ci.ReportSectionKindFindings:
		if section.Findings == nil {
			return ci.ReportSection{}, false
		}
		rows := make([]ci.FindingRow, 0, len(section.Findings.Rows))
		for _, row := range section.Findings.Rows {
			if row.Status == ci.FindingRowStatusWarn || row.Status == ci.FindingRowStatusFail {
				rows = append(rows, row)
			}
		}
		if len(rows) == 0 {
			return ci.ReportSection{}, false
		}
		section.Findings = &ci.FindingsSection{Rows: rows}
		return section, true
	case ci.ReportSectionKindDependencyUpdates:
		if section.DependencyUpdates == nil {
			return ci.ReportSection{}, false
		}
		rows := make([]ci.DependencyUpdateRow, 0, len(section.DependencyUpdates.Rows))
		for i := range section.DependencyUpdates.Rows {
			row := section.DependencyUpdates.Rows[i]
			if row.Status == ci.DependencyUpdateStatusUpdateAvailable || row.Status == ci.DependencyUpdateStatusApplied {
				rows = append(rows, row)
			}
		}
		if len(rows) == 0 {
			return ci.ReportSection{}, false
		}
		section.DependencyUpdates = &ci.DependencyUpdatesSection{Rows: rows}
		return section, true
	case ci.ReportSectionKindOverview:
		return ci.ReportSection{}, false
	case ci.ReportSectionKindModuleTable:
		return section, true
	default:
		return section, true
	}
}

func renderMarkdownSection(section ci.ReportSection) string {
	switch section.Kind {
	case ci.ReportSectionKindOverview:
		return renderMarkdownOverviewSection(section)
	case ci.ReportSectionKindModuleTable:
		return renderMarkdownModuleTableSection(section)
	case ci.ReportSectionKindEstimateChanges:
		return renderMarkdownEstimateChangesSection(section)
	case ci.ReportSectionKindFindings:
		return renderMarkdownFindingsSection(section)
	case ci.ReportSectionKindDependencyUpdates:
		return renderMarkdownDependencyUpdatesSection(section)
	default:
		return ""
	}
}

func renderMarkdownOverviewSection(section ci.ReportSection) string {
	if section.Overview == nil {
		return ""
	}

	var sb strings.Builder
	sb.WriteString(renderStats(planStats{
		Total:     section.Overview.PlanStats.Total,
		Success:   section.Overview.PlanStats.Success,
		NoChanges: section.Overview.PlanStats.NoChanges,
		Changes:   section.Overview.PlanStats.Changes,
		Failed:    section.Overview.PlanStats.Failed,
		Pending:   section.Overview.PlanStats.Pending,
		Running:   section.Overview.PlanStats.Running,
	}))

	for _, overview := range section.Overview.Reports {
		sb.WriteString("\n")
		fmt.Fprintf(&sb, "- %s %s", reportStatusIcon(overview.Status), overview.Title)
		if overview.Summary != "" {
			sb.WriteString(": ")
			sb.WriteString(overview.Summary)
		}
	}

	return sb.String()
}

func renderMarkdownModuleTableSection(section ci.ReportSection) string {
	if section.ModuleTable == nil {
		return ""
	}

	var sb strings.Builder
	fmt.Fprintf(&sb, "### %s\n\n", section.Title)

	hasCostData := false
	for i := range section.ModuleTable.Rows {
		if section.ModuleTable.Rows[i].HasEstimate {
			hasCostData = true
			break
		}
	}

	if hasCostData {
		sb.WriteString("| Status | Module | Summary | Cost |\n")
		sb.WriteString("|:------:|--------|--------|------|\n")
	} else {
		sb.WriteString("| Status | Module | Summary |\n")
		sb.WriteString("|:------:|--------|--------|\n")
	}

	for i := range section.ModuleTable.Rows {
		sb.WriteString(renderPlanRow(moduleTableRowAsModulePlan(section.ModuleTable.Rows[i]), hasCostData))
	}

	for i := range section.ModuleTable.Rows {
		row := section.ModuleTable.Rows[i]
		if row.StructuredDetails == "" && row.RawPlanOutput == "" && row.Error == "" {
			continue
		}
		sb.WriteString(renderExpandableDetails(moduleTableRowAsModulePlan(row)))
	}

	return strings.TrimSpace(sb.String())
}

func renderMarkdownEstimateChangesSection(section ci.ReportSection) string {
	if section.EstimateChanges == nil {
		return ""
	}

	var sb strings.Builder
	sb.WriteString(renderSectionHeader(section))
	sb.WriteString("| Module | Before | After | Diff | Notes |\n")
	sb.WriteString("|--------|--------|-------|------|-------|\n")
	for _, row := range section.EstimateChanges.Rows {
		before := "-"
		after := "-"
		diff := "-"
		notes := row.Notes
		if row.HasEstimate {
			before = FormatMonthlyCost(row.Before)
			after = FormatMonthlyCost(row.After)
			diff = FormatEstimateDiff(row.Diff)
		}
		if row.Error != "" {
			notes = row.Error
		}
		fmt.Fprintf(&sb, "| %s | %s | %s | %s | %s |\n", row.ModulePath, before, after, diff, notes)
	}
	return strings.TrimSpace(sb.String())
}

func renderMarkdownFindingsSection(section ci.ReportSection) string {
	if section.Findings == nil {
		return ""
	}

	var sb strings.Builder
	sb.WriteString(renderSectionHeader(section))
	for _, row := range section.Findings.Rows {
		fmt.Fprintf(&sb, "**%s** (%s)\n", row.ModulePath, row.Status)
		for _, finding := range row.Findings {
			prefix := ":warning:"
			if finding.Severity == ci.FindingSeverityFail {
				prefix = ":x:"
			}
			fmt.Fprintf(&sb, "- %s %s", prefix, finding.Message)
			if finding.Namespace != "" {
				fmt.Fprintf(&sb, " (%s)", finding.Namespace)
			}
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}
	return strings.TrimSpace(sb.String())
}

func renderMarkdownDependencyUpdatesSection(section ci.ReportSection) string {
	if section.DependencyUpdates == nil {
		return ""
	}

	var sb strings.Builder
	sb.WriteString(renderSectionHeader(section))
	providers, modules := splitDependencyUpdateRows(section.DependencyUpdates.Rows)
	if len(providers) > 0 {
		sb.WriteString("### Providers\n\n")
		sb.WriteString("| Module | Provider | Current | Latest | Status |\n")
		sb.WriteString("|--------|----------|---------|--------|--------|\n")
		for i := range providers {
			row := providers[i]
			fmt.Fprintf(&sb, "| %s | %s | %s | %s | %s |\n",
				row.ModulePath, row.Name, displayValue(row.Current), displayValue(row.Latest), dependencyUpdateStatusLabel(row.Status, row.Issue))
		}
		sb.WriteString("\n")
	}
	if len(modules) > 0 {
		sb.WriteString("### Modules\n\n")
		sb.WriteString("| Module | Source | Current | Latest | Status |\n")
		sb.WriteString("|--------|--------|---------|--------|--------|\n")
		for i := range modules {
			row := modules[i]
			fmt.Fprintf(&sb, "| %s | %s | %s | %s | %s |\n",
				row.ModulePath, row.Name, displayValue(row.Current), displayValue(row.Latest), dependencyUpdateStatusLabel(row.Status, row.Issue))
		}
	}
	return strings.TrimSpace(sb.String())
}

func renderSectionHeader(section ci.ReportSection) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "### %s %s\n\n", reportStatusIcon(section.Status), sectionTitle(section))
	fmt.Fprintf(&sb, "**Status:** %s", section.Status)
	if section.SectionSummary != "" {
		fmt.Fprintf(&sb, " — %s", section.SectionSummary)
	}
	sb.WriteString("\n\n")
	return sb.String()
}

func sectionTitle(section ci.ReportSection) string {
	if section.Title != "" {
		return section.Title
	}
	switch section.Kind {
	case ci.ReportSectionKindEstimateChanges:
		return "Cost Estimation"
	case ci.ReportSectionKindFindings:
		return "Policy Check"
	case ci.ReportSectionKindDependencyUpdates:
		return "Dependency Update Check"
	case ci.ReportSectionKindOverview:
		return "Summary"
	case ci.ReportSectionKindModuleTable:
		return "Terraform Plan"
	default:
		return string(section.Kind)
	}
}

func reportStatusIcon(status ci.ReportStatus) string {
	switch status {
	case ci.ReportStatusPass:
		return "pass"
	case ci.ReportStatusWarn:
		return "warn"
	case ci.ReportStatusFail:
		return "fail"
	default:
		return string(status)
	}
}

type planStats struct {
	Total     int
	Success   int
	NoChanges int
	Changes   int
	Failed    int
	Pending   int
	Running   int
}

func calculateStats(plans []ci.ModulePlan) planStats {
	var stats planStats
	stats.Total = len(plans)
	for i := range plans {
		switch plans[i].Status {
		case ci.PlanStatusSuccess, ci.PlanStatusNoChanges:
			stats.NoChanges++
		case ci.PlanStatusChanges:
			stats.Changes++
		case ci.PlanStatusFailed:
			stats.Failed++
		case ci.PlanStatusPending:
			stats.Pending++
		case ci.PlanStatusRunning:
			stats.Running++
		}
	}
	stats.Success = stats.NoChanges + stats.Changes
	return stats
}

func renderStats(stats planStats) string {
	var parts []string
	if stats.Changes > 0 {
		parts = append(parts, fmt.Sprintf("**%d** with changes", stats.Changes))
	}
	if stats.NoChanges > 0 {
		parts = append(parts, fmt.Sprintf("**%d** no changes", stats.NoChanges))
	}
	if stats.Failed > 0 {
		parts = append(parts, fmt.Sprintf("**%d** failed", stats.Failed))
	}
	if stats.Running > 0 {
		parts = append(parts, fmt.Sprintf("**%d** running", stats.Running))
	}
	if stats.Pending > 0 {
		parts = append(parts, fmt.Sprintf("**%d** pending", stats.Pending))
	}
	if len(parts) == 0 {
		return fmt.Sprintf("**%d** modules analyzed", stats.Total)
	}
	return fmt.Sprintf("**%d** modules: %s", stats.Total, strings.Join(parts, " | "))
}

func groupByEnvironment(plans []ci.ModulePlan) map[string][]ci.ModulePlan {
	result := make(map[string][]ci.ModulePlan)
	for i := range plans {
		env := plans[i].Get("environment")
		if env == "" {
			env = "default"
		}
		result[env] = append(result[env], plans[i])
	}
	return result
}

func sortedKeys(m map[string][]ci.ModulePlan) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func visibleEnvironmentPlans(plans []ci.ModulePlan) []ci.ModulePlan {
	visible := make([]ci.ModulePlan, 0, len(plans))
	for i := range plans {
		if plans[i].Status == ci.PlanStatusChanges || plans[i].Status == ci.PlanStatusFailed {
			visible = append(visible, plans[i])
		}
	}
	return visible
}

func moduleTableRowAsModulePlan(row ci.ModuleTableRow) *ci.ModulePlan {
	return &ci.ModulePlan{
		ModuleID:          row.ModuleID,
		ModulePath:        row.ModulePath,
		Status:            row.Status,
		Summary:           row.Summary,
		Error:             row.Error,
		StructuredDetails: row.StructuredDetails,
		RawPlanOutput:     row.RawPlanOutput,
		EstimateBefore:    row.EstimateBefore,
		EstimateAfter:     row.EstimateAfter,
		EstimateDiff:      row.EstimateDiff,
		HasEstimate:       row.HasEstimate,
	}
}

func renderPlanRow(p *ci.ModulePlan, includeCost bool) string {
	status := statusIcon(p.Status)
	module := fmt.Sprintf("`%s`", p.ModuleID)
	summary := p.Summary
	if p.Error != "" {
		summary = "err: " + Truncate(p.Error, maxErrorLength)
	}
	if summary == "" {
		summary = "-"
	}
	if !includeCost {
		return fmt.Sprintf("| %s | %s | %s |\n", status, module, summary)
	}
	return fmt.Sprintf("| %s | %s | %s | %s |\n", status, module, summary, FormatCostCell(p))
}

func FormatCostCell(p *ci.ModulePlan) string {
	if !p.HasEstimate {
		return "-"
	}
	if p.EstimateDiff == 0 {
		return FormatMonthlyCost(p.EstimateAfter)
	}
	return fmt.Sprintf("%s %s -> %s", FormatMonthlyCost(p.EstimateBefore), FormatEstimateDiff(p.EstimateDiff), FormatMonthlyCost(p.EstimateAfter))
}

func FormatMonthlyCost(cost float64) string {
	if cost == 0 {
		return "$0"
	}
	if cost < minCostThreshold {
		return "<$0.01"
	}
	if cost >= thousandCostThreshold {
		return fmt.Sprintf("$%.0f", cost)
	}
	if cost >= 1 {
		return fmt.Sprintf("$%.2f", cost)
	}
	return fmt.Sprintf("$%.4f", cost)
}

func FormatEstimateDiff(diff float64) string {
	if diff == 0 {
		return "$0"
	}
	if diff > 0 {
		if diff >= thousandCostThreshold {
			return fmt.Sprintf("+$%.0f", diff)
		}
		if diff >= 1 {
			return fmt.Sprintf("+$%.2f", diff)
		}
		return fmt.Sprintf("+$%.4f", diff)
	}
	diff = -diff
	if diff >= thousandCostThreshold {
		return fmt.Sprintf("-$%.0f", diff)
	}
	if diff >= 1 {
		return fmt.Sprintf("-$%.2f", diff)
	}
	return fmt.Sprintf("-$%.4f", diff)
}

func statusIcon(status ci.PlanStatus) string {
	switch status {
	case ci.PlanStatusSuccess, ci.PlanStatusNoChanges:
		return "ok"
	case ci.PlanStatusChanges:
		return "changes"
	case ci.PlanStatusFailed:
		return "failed"
	case ci.PlanStatusPending:
		return "pending"
	case ci.PlanStatusRunning:
		return "running"
	default:
		return "?"
	}
}

func renderExpandableDetails(p *ci.ModulePlan) string {
	var sb strings.Builder
	title := p.ModuleID
	if p.Summary != "" && p.Summary != "No changes" {
		title = fmt.Sprintf("%s (%s)", p.ModuleID, p.Summary)
	}
	if p.Status == ci.PlanStatusFailed {
		title = "FAILED " + p.ModuleID
	}

	fmt.Fprintf(&sb, "\n<details>\n<summary>%s</summary>\n\n", title)
	if p.StructuredDetails != "" {
		sb.WriteString(p.StructuredDetails)
		sb.WriteString("\n\n")
	}
	if p.RawPlanOutput != "" {
		sb.WriteString("<details>\n<summary>Full plan output</summary>\n\n")
		sb.WriteString("```diff\n")
		sb.WriteString(Truncate(p.RawPlanOutput, maxDetailsLength))
		sb.WriteString("\n```\n")
		sb.WriteString("</details>\n")
	}
	sb.WriteString("</details>\n")
	return sb.String()
}

func splitDependencyUpdateRows(rows []ci.DependencyUpdateRow) (providers, modules []ci.DependencyUpdateRow) {
	providers = make([]ci.DependencyUpdateRow, 0, len(rows))
	modules = make([]ci.DependencyUpdateRow, 0, len(rows))
	for i := range rows {
		row := rows[i]
		switch row.Kind {
		case ci.DependencyKindProvider:
			providers = append(providers, row)
		case ci.DependencyKindModule:
			modules = append(modules, row)
		}
	}
	return providers, modules
}

func dependencyUpdateStatusLabel(status ci.DependencyUpdateStatus, issue string) string {
	switch status {
	case ci.DependencyUpdateStatusUpdateAvailable:
		return "update available"
	case ci.DependencyUpdateStatusApplied:
		return "applied"
	case ci.DependencyUpdateStatusSkipped:
		return "skipped: " + issue
	case ci.DependencyUpdateStatusError:
		return "error: " + issue
	case ci.DependencyUpdateStatusUpToDate:
		return "up to date"
	default:
		return "up to date"
	}
}

func displayValue(v string) string {
	if v == "" {
		return "-"
	}
	return v
}

func Truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}
