# yaml-language-server: $schema=https://raw.githubusercontent.com/edelwud/terraci/main/terraci.schema.json
structure:
  pattern: "{service}/{environment}/{region}/{module}"

extensions:
  gitlab:
    image: { name: hashicorp/terraform:1.6 }
    terraform_binary: terraform
    plan_enabled: true
    auto_approve: false
    mr:
      comment: { enabled: true }

  cost:
    cache_dir: .terraci/pricing
    cache_ttl: "24h"
    providers:
      aws:
        enabled: true

  summary: {}
