# yaml-language-server: $schema=https://raw.githubusercontent.com/edelwud/terraci/main/.terraci.schema.json
service_dir: .terraci
structure:
    pattern: '{service}/{environment}/{region}/{module}'
plugins:
    github:
        auto_approve: false
        init_enabled: true
        job_defaults:
            steps_before:
                - uses: actions/checkout@v4
                - uses: hashicorp/setup-terraform@v3
        plan_enabled: true
        pr:
            comment:
                enabled: true
        runs_on: ubuntu-latest
        terraform_binary: terraform
    summary: {}
