# yaml-language-server: $schema=https://raw.githubusercontent.com/edelwud/terraci/main/terraci.schema.json
structure:
  pattern: "{service}/{environment}/{region}/{module}"

execution:
  binary: terraform
  plan_enabled: true

extensions:
  gitlab:
    image: { name: hashicorp/terraform:1.6 }
    auto_approve: false
    mr:
      comment: { enabled: true }

  cost:
    blob_cache:
      backend: diskblob
      namespace: cost/pricing
      ttl: "24h"
    providers:
      aws:
        enabled: true

  summary: {}
