# yaml-language-server: $schema=https://raw.githubusercontent.com/edelwud/terraci/main/terraci.schema.json
structure:
  pattern: "{service}/{environment}/{region}/{module}"

library_modules:
  paths:
    - "_modules"

plugins:
  gitlab:
    terraform_binary: "terraform"
    image:
      name: hashicorp/terraform:1.6
    stages_prefix: "deploy"
    parallelism: 5
    plan_enabled: true
    auto_approve: false
    cache_enabled: true
    init_enabled: true
