package github

import (
	"fmt"

	"go.yaml.in/yaml/v4"
)

// Workflow represents a GitHub Actions workflow
type Workflow struct {
	Name        string            `yaml:"name"`
	On          WorkflowTrigger   `yaml:"on"`
	Permissions map[string]string `yaml:"permissions,omitempty"`
	Env         map[string]string `yaml:"env,omitempty"`
	Concurrency *Concurrency      `yaml:"concurrency,omitempty"`
	Jobs        map[string]*Job   `yaml:"jobs"`
}

// WorkflowTrigger defines when the workflow runs
type WorkflowTrigger struct {
	Push             *PushTrigger `yaml:"push,omitempty"`
	PullRequest      *PRTrigger   `yaml:"pull_request,omitempty"`
	WorkflowDispatch any          `yaml:"workflow_dispatch,omitempty"`
}

// PushTrigger limits push events
type PushTrigger struct {
	Branches []string `yaml:"branches,omitempty"`
}

// PRTrigger limits pull request events
type PRTrigger struct {
	Branches []string `yaml:"branches,omitempty"`
}

// Concurrency controls concurrent runs
type Concurrency struct {
	Group            string `yaml:"group"`
	CancelInProgress bool   `yaml:"cancel-in-progress"`
}

// Job represents a workflow job
type Job struct {
	Name        string            `yaml:"name,omitempty"`
	RunsOn      string            `yaml:"runs-on"`
	Container   *Container        `yaml:"container,omitempty"`
	Needs       []string          `yaml:"needs,omitempty"`
	If          string            `yaml:"if,omitempty"`
	Environment string            `yaml:"environment,omitempty"`
	Concurrency *Concurrency      `yaml:"concurrency,omitempty"`
	Env         map[string]string `yaml:"env,omitempty"`
	Steps       []Step            `yaml:"steps"`
}

// Container specifies a container to run the job in
type Container struct {
	Image string            `yaml:"image"`
	Env   map[string]string `yaml:"env,omitempty"`
}

// Step is one step in a job
type Step struct {
	Name string            `yaml:"name,omitempty"`
	Uses string            `yaml:"uses,omitempty"`
	With map[string]string `yaml:"with,omitempty"`
	Run  string            `yaml:"run,omitempty"`
	Env  map[string]string `yaml:"env,omitempty"`
	If   string            `yaml:"if,omitempty"`
}

// ToYAML serializes the workflow to YAML with a generated-by header
func (w *Workflow) ToYAML() ([]byte, error) {
	data, err := yaml.Marshal(w)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal workflow: %w", err)
	}

	header := []byte("# Generated by terraci — do not edit\n")
	return append(header, data...), nil
}
