# yaml-language-server: $schema=https://raw.githubusercontent.com/edelwud/terraci/main/terraci.schema.json
structure:
  pattern: "{service}/{environment}/{region}/{module}"

gitlab:
  image:
    name: hashicorp/terraform:1.6
  plan_enabled: true
  auto_approve: false
