# yaml-language-server: $schema=https://raw.githubusercontent.com/edelwud/terraci/main/terraci.schema.json
structure:
  pattern: "{service}/{environment}/{region}/{module}"
  allow_submodules: true

gitlab:
  image:
    name: hashicorp/terraform:1.6
  plan_enabled: true
  auto_approve: false

backend:
  type: s3
  key_pattern: "{service}/{environment}/{region}/{module}/terraform.tfstate"
